Matúšova licencia na obsah
Autorské práva (c) 2023-end of the world
---
Matúš Maštena <Shadiness9530@proton.me> (tiež ako TenTypekMatus na GitHub) si ponecháva plné autorské práva na obsah v adresári posts/.
To znamená, že tento softvér nemôžete používať, pokiaľ neodstránite *VŠETOK* obsah adresára posts/. Žiadne informácie z tejto webovej stránky nemôžete použiť vo svojej práci bez uvedenia tejto stránky.
Zvyšok tejto stránky je licencovaný pod licenciou GPL3, ktorú nájdete v koreni repozitára.
Anglickú verziu verziu repozitára taktiež nájdete v koreni repozitára.